clientError: Don't silently drop thrown by Vue.js components
Ice60da09 introduced logging for errors thrown by Vue.js components.
However, the "error.vue" analytics event subscriber signature was
incorrect and so no errors were/are being logged.

Bug: T249826
Change-Id: Ib57a65b8fef9a22a36ef2f7ac26d7a191fe1dac8