clientError: Changes event fields.
- Field 'type' now 'error_class' ('type' is special in logstash).
- Field 'name' now gets value from errorObj.constructor.name
- Field 'file_url' added, value set to URL part of error location
- Field 'url' value now set to location.href
- Field 'meta.domain' now set to location.hostname

Depends on revised schema /mediawiki/client/error, see:
https://gerrit.wikimedia.org/r/#/c/schemas/event/primary/+/580980

Bug: T226986
Depends-On: I16eb836ee564d7e4c5ef21fb44330a3a72a25b21
Change-Id: I6e75b4b466aeb133303160a4542693d477c85bf7