clientError: Log errors thrown by Vue.js components
Changes:

- Add the ErrorDescriptor type, which describes the shape of the object
  required to log an error to Wikimedia's eventgate-logging-external
  error intake service [0] with

- Extract processErrorLoggerError(), which creates an error descriptor
  from an object logged on the "global.error" topic. Also extract
  shouldLog() and log() so that the encapsulated logic can be reused and
  tested in isolation

- Add processVueError(), which creates an error descriptor from an Error
  object. Use this function and the above to log errors in Vue.js
  components.

- Stop logging errors without a stack trace given we are unable to easily
  debug such issues.

[0] https://wikitech.wikimedia.org/wiki/Event_Platform/EventGate#eventgate-logging-external

Bug: T249826
Change-Id: Ice60da0986c5ad20791feb67164abdd8ea466f6c