clientError: Log active gadgets
Log the list of gadgets that were successfully loaded and executed
before the error happened. This can help identify errors caused
by gadgets interfering with site functionality.

The list of enabled gadgets is somewhat personalised, but compared
to other information we are already logging that's relatively minor,
and it takes effort to look up (someone just casually looking at
Logstash won't learn the user's identity).

Change-Id: I02833edd15559fb3c85efae3dbc20f010340fd95