clientError: Replace inline disables with eslint-disable camelcase
Camel case variables are ingrained enough that these are not going
to be introduced by accident in a file like this. We can reach for
eslint-disable to set this on at least the function level to make
changes a bit easier and intuitive.

Change-Id: Iacf8be94f9ea0d1d724fd3ab471a34b12dbdb311