Restore dependency on mediawiki.Uri
> Exception in module-execute in module ext.wikimediaEvents:
> TypeError: mw.Uri is not a function TypeError: mw.Uri is not a function

Accidentally removed in 7decf38.

Change-Id: I01509f9c2d5b73305dbf1f5c1a33c64d5d15f9f5