clientError: Import private file directly instead of repacking another module
Exampe of new feature from I9fca9fdf9 in MediaWiki core.

Bug: T250045
Depends-On: I9fca9fdf9b7623b1a759a30f52872bdc269493b7
Change-Id: I53ca51a0a26e82461c4a3530126ebcf9f2f9086f