clientError: Restore client error logging output
The function returns true if the error is not subject to
error logging, introduced in 44148d523

* The file_url should be logged as undefined if missing
  and sent to the intake service
* The message key should forward errorMessage per line 236.

Additional:
Function name shouldn't be confusing.

The function returns true if the error is not subject to
error logging.

Bug: T277094
Change-Id: I7093ed4b170c5b42ad25f3e6da9ea68f30992dc0