clientError: Modernize test syntax
Plus:

* Remove unused mw.util stub.
* Keep mw.user stub.

  The last unit tests in extensions that depended skin or user
  context were fixed in 2020. MediaWiki's QUnit runtime no longer
  varies by those factors. Akin to PHPUnit, tests no longer inherit
  the live wiki context beyond deciding what extensions to load/test.

  But, this test wasn't stubbing it out so much as overriding it
  to emulate logged-in instead of the default logged-out.
  Need a stub of that either way :)

* Simplify code by using assert.propContains().

* Simplify linter config, using new eslint present.

Change-Id: I6360c9f76083150e382845e6715df970c9d90938